apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: cicdprueba
spec:
  replicas: 3
  selector:
    matchLabels:
      name: cicdprueba
  template:
    metadata:
      labels:
        name: cicdprueba
    spec:
      containers:
      - name: cicdprueba
        image: mescorza/cicdprueba
        ports:
        - containerPort: 80
          name: http
